import enum
import math

from typing import Optional

from albot.view import Location


class Zone(enum.Enum):
    PINK_START = 'PINK_START'
    BOTTOM_LEFT = 'BOTTOM_LEFT'
    BOTTOM_RIGHT = 'BOTTOM_RIGHT'
    BOTTOM_CENTRE = 'BOTTOM_CENTRE'
    YELLOW_START = 'YELLOW_START'
    PINK_TOP_CORNER = 'PINK_TOP_CORNER'
    YELLOW_TOP_CORNER = 'YELLOW_TOP_CORNER'
    TOP_CENTRE = 'TOP_CENTRE'
    TOP_LEFT = 'TOP_LEFT'
    TOP_RIGHT = 'TOP_RIGHT'
    LEFT_TRANSITION = 'LEFT_TRANSITION'
    RIGHT_TRANSITION = 'RIGHT_TRANSITION'


def get_zone(location: Location) -> Zone:
    if location.x < -5.575:
        if location.y > 2:
            return Zone.PINK_TOP_CORNER
        elif location.y < -2.6:
            return Zone.BOTTOM_LEFT
        else:
            return Zone.PINK_START
    elif location.x < -2:
        if location.y > 0.75:
            return Zone.TOP_LEFT
        elif location.y > -0.9:
            return Zone.LEFT_TRANSITION
        else:
            return Zone.BOTTOM_LEFT
    elif location.x < 2:
        if location.y > 0:
            return Zone.TOP_CENTRE
        else:
            return Zone.BOTTOM_CENTRE
    elif location.x < 5.575:
        if location.y > 0.75:
            return Zone.TOP_RIGHT
        elif location.y > -0.9:
            return Zone.RIGHT_TRANSITION
        else:
            return Zone.BOTTOM_RIGHT
    else:
        if location.y > 2:
            return Zone.YELLOW_TOP_CORNER
        elif location.y < -2.6:
            return Zone.BOTTOM_RIGHT
        else:
            return Zone.YELLOW_START


STEERING_DIRECTIONS = {
    (Zone.PINK_START, Zone.BOTTOM_LEFT): math.radians(180),
    (Zone.PINK_START, Zone.TOP_LEFT): math.radians(90),
    (Zone.PINK_START, Zone.PINK_TOP_CORNER): math.radians(0),
    (Zone.BOTTOM_LEFT, Zone.BOTTOM_CENTRE): math.radians(90),
    (Zone.BOTTOM_RIGHT, Zone.BOTTOM_CENTRE): math.radians(270),
    (Zone.BOTTOM_CENTRE, Zone.LEFT_TRANSITION): math.radians(320),
    (Zone.BOTTOM_CENTRE, Zone.RIGHT_TRANSITION): math.radians(40),
    (Zone.YELLOW_START, Zone.BOTTOM_RIGHT): math.radians(180),
    (Zone.YELLOW_START, Zone.YELLOW_TOP_CORNER): math.radians(0),
    (Zone.YELLOW_START, Zone.TOP_RIGHT): math.radians(270),
    (Zone.PINK_TOP_CORNER, Zone.TOP_LEFT): math.radians(120),
    (Zone.YELLOW_TOP_CORNER, Zone.TOP_RIGHT): math.radians(240),
    (Zone.TOP_CENTRE, Zone.TOP_LEFT): math.radians(280),
    (Zone.TOP_CENTRE, Zone.TOP_RIGHT): math.radians(80),
    (Zone.TOP_LEFT, Zone.LEFT_TRANSITION): math.radians(180),
    (Zone.TOP_RIGHT, Zone.RIGHT_TRANSITION): math.radians(180),
    (Zone.LEFT_TRANSITION, Zone.BOTTOM_LEFT): math.radians(180),
    (Zone.RIGHT_TRANSITION, Zone.BOTTOM_RIGHT): math.radians(180),
}

for (src, dst), angle in list(STEERING_DIRECTIONS.items()):
    STEERING_DIRECTIONS[dst, src] = (math.radians(180) + angle) % math.tau


ROUTING_PRE_DROP = {
    (Zone.PINK_START, Zone.PINK_TOP_CORNER): Zone.PINK_TOP_CORNER,
    (Zone.PINK_START, Zone.BOTTOM_LEFT): Zone.BOTTOM_LEFT,
    (Zone.PINK_START, Zone.BOTTOM_CENTRE): Zone.BOTTOM_LEFT,
    (Zone.PINK_START, Zone.BOTTOM_RIGHT): Zone.BOTTOM_LEFT,
    (Zone.PINK_START, Zone.LEFT_TRANSITION): Zone.BOTTOM_LEFT,
    (Zone.PINK_START, Zone.RIGHT_TRANSITION): Zone.BOTTOM_LEFT,
    (Zone.PINK_START, Zone.YELLOW_START): Zone.BOTTOM_LEFT,
    (Zone.PINK_START, Zone.TOP_LEFT): Zone.BOTTOM_LEFT,
    (Zone.PINK_START, Zone.TOP_RIGHT): Zone.BOTTOM_LEFT,
    (Zone.PINK_START, Zone.YELLOW_TOP_CORNER): Zone.BOTTOM_LEFT,
    (Zone.PINK_START, Zone.TOP_CENTRE): Zone.BOTTOM_LEFT,
    (Zone.PINK_TOP_CORNER, Zone.PINK_START): Zone.PINK_START,
    (Zone.PINK_TOP_CORNER, Zone.BOTTOM_LEFT): Zone.PINK_START,
    (Zone.PINK_TOP_CORNER, Zone.BOTTOM_CENTRE): Zone.PINK_START,
    (Zone.PINK_TOP_CORNER, Zone.BOTTOM_RIGHT): Zone.PINK_START,
    (Zone.PINK_TOP_CORNER, Zone.LEFT_TRANSITION): Zone.PINK_START,
    (Zone.PINK_TOP_CORNER, Zone.RIGHT_TRANSITION): Zone.PINK_START,
    (Zone.PINK_TOP_CORNER, Zone.YELLOW_START): Zone.PINK_START,
    (Zone.PINK_TOP_CORNER, Zone.TOP_LEFT): Zone.PINK_START,
    (Zone.PINK_TOP_CORNER, Zone.TOP_RIGHT): Zone.PINK_START,
    (Zone.PINK_TOP_CORNER, Zone.YELLOW_TOP_CORNER): Zone.PINK_START,
    (Zone.PINK_TOP_CORNER, Zone.TOP_CENTRE): Zone.PINK_START,
    (Zone.BOTTOM_LEFT, Zone.PINK_START): Zone.PINK_START,
    (Zone.BOTTOM_LEFT, Zone.BOTTOM_CENTRE): Zone.BOTTOM_CENTRE,
    (Zone.BOTTOM_LEFT, Zone.PINK_TOP_CORNER): Zone.PINK_START,
    (Zone.BOTTOM_LEFT, Zone.BOTTOM_RIGHT): Zone.BOTTOM_CENTRE,
    (Zone.BOTTOM_LEFT, Zone.LEFT_TRANSITION): Zone.BOTTOM_CENTRE,
    (Zone.BOTTOM_LEFT, Zone.RIGHT_TRANSITION): Zone.BOTTOM_CENTRE,
    (Zone.BOTTOM_LEFT, Zone.YELLOW_START): Zone.BOTTOM_CENTRE,
    (Zone.BOTTOM_LEFT, Zone.TOP_LEFT): Zone.BOTTOM_CENTRE,
    (Zone.BOTTOM_LEFT, Zone.TOP_RIGHT): Zone.BOTTOM_CENTRE,
    (Zone.BOTTOM_LEFT, Zone.YELLOW_TOP_CORNER): Zone.BOTTOM_CENTRE,
    (Zone.BOTTOM_LEFT, Zone.TOP_CENTRE): Zone.BOTTOM_CENTRE,
    (Zone.BOTTOM_CENTRE, Zone.BOTTOM_LEFT): Zone.BOTTOM_LEFT,
    (Zone.BOTTOM_CENTRE, Zone.BOTTOM_RIGHT): Zone.BOTTOM_RIGHT,
    (Zone.BOTTOM_CENTRE, Zone.LEFT_TRANSITION): Zone.LEFT_TRANSITION,
    (Zone.BOTTOM_CENTRE, Zone.RIGHT_TRANSITION): Zone.RIGHT_TRANSITION,
    (Zone.BOTTOM_CENTRE, Zone.PINK_START): Zone.BOTTOM_LEFT,
    (Zone.BOTTOM_CENTRE, Zone.YELLOW_START): Zone.BOTTOM_RIGHT,
    (Zone.BOTTOM_CENTRE, Zone.TOP_LEFT): Zone.LEFT_TRANSITION,
    (Zone.BOTTOM_CENTRE, Zone.TOP_RIGHT): Zone.RIGHT_TRANSITION,
    (Zone.BOTTOM_CENTRE, Zone.PINK_TOP_CORNER): Zone.BOTTOM_LEFT,
    (Zone.BOTTOM_CENTRE, Zone.YELLOW_TOP_CORNER): Zone.BOTTOM_RIGHT,
    (Zone.BOTTOM_CENTRE, Zone.TOP_CENTRE): Zone.LEFT_TRANSITION,
    (Zone.BOTTOM_RIGHT, Zone.BOTTOM_CENTRE): Zone.BOTTOM_CENTRE,
    (Zone.BOTTOM_RIGHT, Zone.YELLOW_START): Zone.YELLOW_START,
    (Zone.BOTTOM_RIGHT, Zone.BOTTOM_LEFT): Zone.BOTTOM_CENTRE,
    (Zone.BOTTOM_RIGHT, Zone.LEFT_TRANSITION): Zone.BOTTOM_CENTRE,
    (Zone.BOTTOM_RIGHT, Zone.RIGHT_TRANSITION): Zone.BOTTOM_CENTRE,
    (Zone.BOTTOM_RIGHT, Zone.YELLOW_TOP_CORNER): Zone.YELLOW_START,
    (Zone.BOTTOM_RIGHT, Zone.PINK_START): Zone.BOTTOM_CENTRE,
    (Zone.BOTTOM_RIGHT, Zone.TOP_LEFT): Zone.BOTTOM_CENTRE,
    (Zone.BOTTOM_RIGHT, Zone.TOP_RIGHT): Zone.BOTTOM_CENTRE,
    (Zone.BOTTOM_RIGHT, Zone.PINK_TOP_CORNER): Zone.BOTTOM_CENTRE,
    (Zone.BOTTOM_RIGHT, Zone.TOP_CENTRE): Zone.BOTTOM_CENTRE,
    (Zone.YELLOW_START, Zone.BOTTOM_RIGHT): Zone.BOTTOM_RIGHT,
    (Zone.YELLOW_START, Zone.YELLOW_TOP_CORNER): Zone.YELLOW_TOP_CORNER,
    (Zone.YELLOW_START, Zone.BOTTOM_CENTRE): Zone.BOTTOM_RIGHT,
    (Zone.YELLOW_START, Zone.BOTTOM_LEFT): Zone.BOTTOM_RIGHT,
    (Zone.YELLOW_START, Zone.LEFT_TRANSITION): Zone.BOTTOM_RIGHT,
    (Zone.YELLOW_START, Zone.RIGHT_TRANSITION): Zone.BOTTOM_RIGHT,
    (Zone.YELLOW_START, Zone.PINK_START): Zone.BOTTOM_RIGHT,
    (Zone.YELLOW_START, Zone.TOP_LEFT): Zone.BOTTOM_RIGHT,
    (Zone.YELLOW_START, Zone.TOP_RIGHT): Zone.BOTTOM_RIGHT,
    (Zone.YELLOW_START, Zone.PINK_TOP_CORNER): Zone.BOTTOM_RIGHT,
    (Zone.YELLOW_START, Zone.TOP_CENTRE): Zone.BOTTOM_RIGHT,
    (Zone.LEFT_TRANSITION, Zone.BOTTOM_CENTRE): Zone.BOTTOM_CENTRE,
    (Zone.LEFT_TRANSITION, Zone.TOP_LEFT): Zone.TOP_LEFT,
    (Zone.LEFT_TRANSITION, Zone.BOTTOM_LEFT): Zone.BOTTOM_CENTRE,
    (Zone.LEFT_TRANSITION, Zone.BOTTOM_RIGHT): Zone.BOTTOM_CENTRE,
    (Zone.LEFT_TRANSITION, Zone.RIGHT_TRANSITION): Zone.BOTTOM_CENTRE,
    (Zone.LEFT_TRANSITION, Zone.TOP_CENTRE): Zone.TOP_LEFT,
    (Zone.LEFT_TRANSITION, Zone.PINK_START): Zone.BOTTOM_CENTRE,
    (Zone.LEFT_TRANSITION, Zone.YELLOW_START): Zone.BOTTOM_CENTRE,
    (Zone.LEFT_TRANSITION, Zone.TOP_RIGHT): Zone.BOTTOM_CENTRE,
    (Zone.LEFT_TRANSITION, Zone.PINK_TOP_CORNER): Zone.BOTTOM_CENTRE,
    (Zone.LEFT_TRANSITION, Zone.YELLOW_TOP_CORNER): Zone.BOTTOM_CENTRE,
    (Zone.RIGHT_TRANSITION, Zone.BOTTOM_CENTRE): Zone.BOTTOM_CENTRE,
    (Zone.RIGHT_TRANSITION, Zone.TOP_RIGHT): Zone.TOP_RIGHT,
    (Zone.RIGHT_TRANSITION, Zone.BOTTOM_LEFT): Zone.BOTTOM_CENTRE,
    (Zone.RIGHT_TRANSITION, Zone.BOTTOM_RIGHT): Zone.BOTTOM_CENTRE,
    (Zone.RIGHT_TRANSITION, Zone.LEFT_TRANSITION): Zone.BOTTOM_CENTRE,
    (Zone.RIGHT_TRANSITION, Zone.TOP_CENTRE): Zone.TOP_RIGHT,
    (Zone.RIGHT_TRANSITION, Zone.PINK_START): Zone.BOTTOM_CENTRE,
    (Zone.RIGHT_TRANSITION, Zone.YELLOW_START): Zone.BOTTOM_CENTRE,
    (Zone.RIGHT_TRANSITION, Zone.TOP_LEFT): Zone.BOTTOM_CENTRE,
    (Zone.RIGHT_TRANSITION, Zone.PINK_TOP_CORNER): Zone.BOTTOM_CENTRE,
    (Zone.RIGHT_TRANSITION, Zone.YELLOW_TOP_CORNER): Zone.BOTTOM_CENTRE,
    (Zone.YELLOW_TOP_CORNER, Zone.YELLOW_START): Zone.YELLOW_START,
    (Zone.YELLOW_TOP_CORNER, Zone.BOTTOM_RIGHT): Zone.YELLOW_START,
    (Zone.YELLOW_TOP_CORNER, Zone.BOTTOM_CENTRE): Zone.YELLOW_START,
    (Zone.YELLOW_TOP_CORNER, Zone.BOTTOM_LEFT): Zone.YELLOW_START,
    (Zone.YELLOW_TOP_CORNER, Zone.LEFT_TRANSITION): Zone.YELLOW_START,
    (Zone.YELLOW_TOP_CORNER, Zone.RIGHT_TRANSITION): Zone.YELLOW_START,
    (Zone.YELLOW_TOP_CORNER, Zone.PINK_START): Zone.YELLOW_START,
    (Zone.YELLOW_TOP_CORNER, Zone.TOP_LEFT): Zone.YELLOW_START,
    (Zone.YELLOW_TOP_CORNER, Zone.TOP_RIGHT): Zone.YELLOW_START,
    (Zone.YELLOW_TOP_CORNER, Zone.PINK_TOP_CORNER): Zone.YELLOW_START,
    (Zone.YELLOW_TOP_CORNER, Zone.TOP_CENTRE): Zone.YELLOW_START,
    (Zone.TOP_CENTRE, Zone.TOP_LEFT): Zone.TOP_LEFT,
    (Zone.TOP_CENTRE, Zone.TOP_RIGHT): Zone.TOP_RIGHT,
    (Zone.TOP_CENTRE, Zone.LEFT_TRANSITION): Zone.TOP_LEFT,
    (Zone.TOP_CENTRE, Zone.RIGHT_TRANSITION): Zone.TOP_RIGHT,
    (Zone.TOP_CENTRE, Zone.BOTTOM_CENTRE): Zone.TOP_LEFT,
    (Zone.TOP_CENTRE, Zone.BOTTOM_LEFT): Zone.TOP_LEFT,
    (Zone.TOP_CENTRE, Zone.BOTTOM_RIGHT): Zone.TOP_LEFT,
    (Zone.TOP_CENTRE, Zone.PINK_START): Zone.TOP_LEFT,
    (Zone.TOP_CENTRE, Zone.YELLOW_START): Zone.TOP_LEFT,
    (Zone.TOP_CENTRE, Zone.PINK_TOP_CORNER): Zone.TOP_LEFT,
    (Zone.TOP_CENTRE, Zone.YELLOW_TOP_CORNER): Zone.TOP_LEFT,
    (Zone.TOP_LEFT, Zone.TOP_CENTRE): Zone.TOP_CENTRE,
    (Zone.TOP_LEFT, Zone.LEFT_TRANSITION): Zone.LEFT_TRANSITION,
    (Zone.TOP_LEFT, Zone.TOP_RIGHT): Zone.TOP_CENTRE,
    (Zone.TOP_LEFT, Zone.BOTTOM_CENTRE): Zone.LEFT_TRANSITION,
    (Zone.TOP_LEFT, Zone.RIGHT_TRANSITION): Zone.TOP_CENTRE,
    (Zone.TOP_LEFT, Zone.BOTTOM_LEFT): Zone.LEFT_TRANSITION,
    (Zone.TOP_LEFT, Zone.BOTTOM_RIGHT): Zone.LEFT_TRANSITION,
    (Zone.TOP_LEFT, Zone.PINK_START): Zone.LEFT_TRANSITION,
    (Zone.TOP_LEFT, Zone.YELLOW_START): Zone.LEFT_TRANSITION,
    (Zone.TOP_LEFT, Zone.PINK_TOP_CORNER): Zone.LEFT_TRANSITION,
    (Zone.TOP_LEFT, Zone.YELLOW_TOP_CORNER): Zone.LEFT_TRANSITION,
    (Zone.TOP_RIGHT, Zone.TOP_CENTRE): Zone.TOP_CENTRE,
    (Zone.TOP_RIGHT, Zone.RIGHT_TRANSITION): Zone.RIGHT_TRANSITION,
    (Zone.TOP_RIGHT, Zone.TOP_LEFT): Zone.TOP_CENTRE,
    (Zone.TOP_RIGHT, Zone.BOTTOM_CENTRE): Zone.RIGHT_TRANSITION,
    (Zone.TOP_RIGHT, Zone.LEFT_TRANSITION): Zone.TOP_CENTRE,
    (Zone.TOP_RIGHT, Zone.BOTTOM_LEFT): Zone.RIGHT_TRANSITION,
    (Zone.TOP_RIGHT, Zone.BOTTOM_RIGHT): Zone.RIGHT_TRANSITION,
    (Zone.TOP_RIGHT, Zone.PINK_START): Zone.RIGHT_TRANSITION,
    (Zone.TOP_RIGHT, Zone.YELLOW_START): Zone.RIGHT_TRANSITION,
    (Zone.TOP_RIGHT, Zone.PINK_TOP_CORNER): Zone.RIGHT_TRANSITION,
    (Zone.TOP_RIGHT, Zone.YELLOW_TOP_CORNER): Zone.RIGHT_TRANSITION,
}

for (src, _), next_hop in ROUTING_PRE_DROP.items():
    assert (src, next_hop) in STEERING_DIRECTIONS

ROUTING_POST_DROP = {
    (Zone.PINK_START, Zone.PINK_TOP_CORNER): Zone.PINK_TOP_CORNER,
    (Zone.PINK_START, Zone.BOTTOM_LEFT): Zone.BOTTOM_LEFT,
    (Zone.PINK_START, Zone.TOP_LEFT): Zone.TOP_LEFT,
    (Zone.PINK_START, Zone.BOTTOM_CENTRE): Zone.BOTTOM_LEFT,
    (Zone.PINK_START, Zone.LEFT_TRANSITION): Zone.BOTTOM_LEFT,
    (Zone.PINK_START, Zone.TOP_CENTRE): Zone.TOP_LEFT,
    (Zone.PINK_START, Zone.BOTTOM_RIGHT): Zone.BOTTOM_LEFT,
    (Zone.PINK_START, Zone.RIGHT_TRANSITION): Zone.BOTTOM_LEFT,
    (Zone.PINK_START, Zone.TOP_RIGHT): Zone.TOP_LEFT,
    (Zone.PINK_START, Zone.YELLOW_START): Zone.BOTTOM_LEFT,
    (Zone.PINK_START, Zone.YELLOW_TOP_CORNER): Zone.TOP_LEFT,
    (Zone.PINK_TOP_CORNER, Zone.PINK_START): Zone.PINK_START,
    (Zone.PINK_TOP_CORNER, Zone.TOP_LEFT): Zone.TOP_LEFT,
    (Zone.PINK_TOP_CORNER, Zone.BOTTOM_LEFT): Zone.PINK_START,
    (Zone.PINK_TOP_CORNER, Zone.LEFT_TRANSITION): Zone.TOP_LEFT,
    (Zone.PINK_TOP_CORNER, Zone.TOP_CENTRE): Zone.TOP_LEFT,
    (Zone.PINK_TOP_CORNER, Zone.BOTTOM_CENTRE): Zone.PINK_START,
    (Zone.PINK_TOP_CORNER, Zone.TOP_RIGHT): Zone.TOP_LEFT,
    (Zone.PINK_TOP_CORNER, Zone.BOTTOM_RIGHT): Zone.PINK_START,
    (Zone.PINK_TOP_CORNER, Zone.RIGHT_TRANSITION): Zone.PINK_START,
    (Zone.PINK_TOP_CORNER, Zone.YELLOW_START): Zone.TOP_LEFT,
    (Zone.PINK_TOP_CORNER, Zone.YELLOW_TOP_CORNER): Zone.TOP_LEFT,
    (Zone.BOTTOM_LEFT, Zone.PINK_START): Zone.PINK_START,
    (Zone.BOTTOM_LEFT, Zone.BOTTOM_CENTRE): Zone.BOTTOM_CENTRE,
    (Zone.BOTTOM_LEFT, Zone.LEFT_TRANSITION): Zone.LEFT_TRANSITION,
    (Zone.BOTTOM_LEFT, Zone.PINK_TOP_CORNER): Zone.PINK_START,
    (Zone.BOTTOM_LEFT, Zone.TOP_LEFT): Zone.PINK_START,
    (Zone.BOTTOM_LEFT, Zone.BOTTOM_RIGHT): Zone.BOTTOM_CENTRE,
    (Zone.BOTTOM_LEFT, Zone.RIGHT_TRANSITION): Zone.BOTTOM_CENTRE,
    (Zone.BOTTOM_LEFT, Zone.TOP_CENTRE): Zone.PINK_START,
    (Zone.BOTTOM_LEFT, Zone.YELLOW_START): Zone.BOTTOM_CENTRE,
    (Zone.BOTTOM_LEFT, Zone.TOP_RIGHT): Zone.BOTTOM_CENTRE,
    (Zone.BOTTOM_LEFT, Zone.YELLOW_TOP_CORNER): Zone.BOTTOM_CENTRE,
    (Zone.BOTTOM_CENTRE, Zone.BOTTOM_LEFT): Zone.BOTTOM_LEFT,
    (Zone.BOTTOM_CENTRE, Zone.BOTTOM_RIGHT): Zone.BOTTOM_RIGHT,
    (Zone.BOTTOM_CENTRE, Zone.LEFT_TRANSITION): Zone.LEFT_TRANSITION,
    (Zone.BOTTOM_CENTRE, Zone.RIGHT_TRANSITION): Zone.RIGHT_TRANSITION,
    (Zone.BOTTOM_CENTRE, Zone.PINK_START): Zone.BOTTOM_LEFT,
    (Zone.BOTTOM_CENTRE, Zone.YELLOW_START): Zone.BOTTOM_RIGHT,
    (Zone.BOTTOM_CENTRE, Zone.TOP_LEFT): Zone.LEFT_TRANSITION,
    (Zone.BOTTOM_CENTRE, Zone.TOP_RIGHT): Zone.RIGHT_TRANSITION,
    (Zone.BOTTOM_CENTRE, Zone.PINK_TOP_CORNER): Zone.BOTTOM_LEFT,
    (Zone.BOTTOM_CENTRE, Zone.YELLOW_TOP_CORNER): Zone.BOTTOM_RIGHT,
    (Zone.BOTTOM_CENTRE, Zone.TOP_CENTRE): Zone.LEFT_TRANSITION,
    (Zone.BOTTOM_RIGHT, Zone.BOTTOM_CENTRE): Zone.BOTTOM_CENTRE,
    (Zone.BOTTOM_RIGHT, Zone.YELLOW_START): Zone.YELLOW_START,
    (Zone.BOTTOM_RIGHT, Zone.RIGHT_TRANSITION): Zone.RIGHT_TRANSITION,
    (Zone.BOTTOM_RIGHT, Zone.BOTTOM_LEFT): Zone.BOTTOM_CENTRE,
    (Zone.BOTTOM_RIGHT, Zone.LEFT_TRANSITION): Zone.BOTTOM_CENTRE,
    (Zone.BOTTOM_RIGHT, Zone.YELLOW_TOP_CORNER): Zone.YELLOW_START,
    (Zone.BOTTOM_RIGHT, Zone.TOP_RIGHT): Zone.YELLOW_START,
    (Zone.BOTTOM_RIGHT, Zone.PINK_START): Zone.BOTTOM_CENTRE,
    (Zone.BOTTOM_RIGHT, Zone.TOP_LEFT): Zone.BOTTOM_CENTRE,
    (Zone.BOTTOM_RIGHT, Zone.TOP_CENTRE): Zone.YELLOW_START,
    (Zone.BOTTOM_RIGHT, Zone.PINK_TOP_CORNER): Zone.BOTTOM_CENTRE,
    (Zone.YELLOW_START, Zone.BOTTOM_RIGHT): Zone.BOTTOM_RIGHT,
    (Zone.YELLOW_START, Zone.YELLOW_TOP_CORNER): Zone.YELLOW_TOP_CORNER,
    (Zone.YELLOW_START, Zone.TOP_RIGHT): Zone.TOP_RIGHT,
    (Zone.YELLOW_START, Zone.BOTTOM_CENTRE): Zone.BOTTOM_RIGHT,
    (Zone.YELLOW_START, Zone.RIGHT_TRANSITION): Zone.BOTTOM_RIGHT,
    (Zone.YELLOW_START, Zone.TOP_CENTRE): Zone.TOP_RIGHT,
    (Zone.YELLOW_START, Zone.BOTTOM_LEFT): Zone.BOTTOM_RIGHT,
    (Zone.YELLOW_START, Zone.LEFT_TRANSITION): Zone.BOTTOM_RIGHT,
    (Zone.YELLOW_START, Zone.TOP_LEFT): Zone.TOP_RIGHT,
    (Zone.YELLOW_START, Zone.PINK_START): Zone.BOTTOM_RIGHT,
    (Zone.YELLOW_START, Zone.PINK_TOP_CORNER): Zone.TOP_RIGHT,
    (Zone.LEFT_TRANSITION, Zone.BOTTOM_CENTRE): Zone.BOTTOM_CENTRE,
    (Zone.LEFT_TRANSITION, Zone.TOP_LEFT): Zone.TOP_LEFT,
    (Zone.LEFT_TRANSITION, Zone.BOTTOM_LEFT): Zone.BOTTOM_LEFT,
    (Zone.LEFT_TRANSITION, Zone.BOTTOM_RIGHT): Zone.BOTTOM_CENTRE,
    (Zone.LEFT_TRANSITION, Zone.RIGHT_TRANSITION): Zone.BOTTOM_CENTRE,
    (Zone.LEFT_TRANSITION, Zone.TOP_CENTRE): Zone.TOP_LEFT,
    (Zone.LEFT_TRANSITION, Zone.PINK_START): Zone.TOP_LEFT,
    (Zone.LEFT_TRANSITION, Zone.PINK_TOP_CORNER): Zone.TOP_LEFT,
    (Zone.LEFT_TRANSITION, Zone.YELLOW_START): Zone.BOTTOM_CENTRE,
    (Zone.LEFT_TRANSITION, Zone.TOP_RIGHT): Zone.BOTTOM_CENTRE,
    (Zone.LEFT_TRANSITION, Zone.YELLOW_TOP_CORNER): Zone.BOTTOM_CENTRE,
    (Zone.RIGHT_TRANSITION, Zone.BOTTOM_CENTRE): Zone.BOTTOM_CENTRE,
    (Zone.RIGHT_TRANSITION, Zone.TOP_RIGHT): Zone.TOP_RIGHT,
    (Zone.RIGHT_TRANSITION, Zone.BOTTOM_RIGHT): Zone.BOTTOM_RIGHT,
    (Zone.RIGHT_TRANSITION, Zone.BOTTOM_LEFT): Zone.BOTTOM_CENTRE,
    (Zone.RIGHT_TRANSITION, Zone.LEFT_TRANSITION): Zone.BOTTOM_CENTRE,
    (Zone.RIGHT_TRANSITION, Zone.TOP_CENTRE): Zone.TOP_RIGHT,
    (Zone.RIGHT_TRANSITION, Zone.YELLOW_START): Zone.TOP_RIGHT,
    (Zone.RIGHT_TRANSITION, Zone.YELLOW_TOP_CORNER): Zone.TOP_RIGHT,
    (Zone.RIGHT_TRANSITION, Zone.PINK_START): Zone.BOTTOM_CENTRE,
    (Zone.RIGHT_TRANSITION, Zone.TOP_LEFT): Zone.BOTTOM_CENTRE,
    (Zone.RIGHT_TRANSITION, Zone.PINK_TOP_CORNER): Zone.BOTTOM_CENTRE,
    (Zone.YELLOW_TOP_CORNER, Zone.YELLOW_START): Zone.YELLOW_START,
    (Zone.YELLOW_TOP_CORNER, Zone.TOP_RIGHT): Zone.TOP_RIGHT,
    (Zone.YELLOW_TOP_CORNER, Zone.BOTTOM_RIGHT): Zone.YELLOW_START,
    (Zone.YELLOW_TOP_CORNER, Zone.RIGHT_TRANSITION): Zone.TOP_RIGHT,
    (Zone.YELLOW_TOP_CORNER, Zone.TOP_CENTRE): Zone.TOP_RIGHT,
    (Zone.YELLOW_TOP_CORNER, Zone.BOTTOM_CENTRE): Zone.YELLOW_START,
    (Zone.YELLOW_TOP_CORNER, Zone.TOP_LEFT): Zone.TOP_RIGHT,
    (Zone.YELLOW_TOP_CORNER, Zone.BOTTOM_LEFT): Zone.YELLOW_START,
    (Zone.YELLOW_TOP_CORNER, Zone.LEFT_TRANSITION): Zone.YELLOW_START,
    (Zone.YELLOW_TOP_CORNER, Zone.PINK_START): Zone.TOP_RIGHT,
    (Zone.YELLOW_TOP_CORNER, Zone.PINK_TOP_CORNER): Zone.TOP_RIGHT,
    (Zone.TOP_CENTRE, Zone.TOP_LEFT): Zone.TOP_LEFT,
    (Zone.TOP_CENTRE, Zone.TOP_RIGHT): Zone.TOP_RIGHT,
    (Zone.TOP_CENTRE, Zone.LEFT_TRANSITION): Zone.TOP_LEFT,
    (Zone.TOP_CENTRE, Zone.PINK_START): Zone.TOP_LEFT,
    (Zone.TOP_CENTRE, Zone.PINK_TOP_CORNER): Zone.TOP_LEFT,
    (Zone.TOP_CENTRE, Zone.RIGHT_TRANSITION): Zone.TOP_RIGHT,
    (Zone.TOP_CENTRE, Zone.YELLOW_START): Zone.TOP_RIGHT,
    (Zone.TOP_CENTRE, Zone.YELLOW_TOP_CORNER): Zone.TOP_RIGHT,
    (Zone.TOP_CENTRE, Zone.BOTTOM_CENTRE): Zone.TOP_LEFT,
    (Zone.TOP_CENTRE, Zone.BOTTOM_LEFT): Zone.TOP_LEFT,
    (Zone.TOP_CENTRE, Zone.BOTTOM_RIGHT): Zone.TOP_RIGHT,
    (Zone.TOP_LEFT, Zone.LEFT_TRANSITION): Zone.LEFT_TRANSITION,
    (Zone.TOP_LEFT, Zone.TOP_CENTRE): Zone.TOP_CENTRE,
    (Zone.TOP_LEFT, Zone.PINK_START): Zone.PINK_START,
    (Zone.TOP_LEFT, Zone.PINK_TOP_CORNER): Zone.PINK_TOP_CORNER,
    (Zone.TOP_LEFT, Zone.BOTTOM_CENTRE): Zone.LEFT_TRANSITION,
    (Zone.TOP_LEFT, Zone.BOTTOM_LEFT): Zone.LEFT_TRANSITION,
    (Zone.TOP_LEFT, Zone.TOP_RIGHT): Zone.TOP_CENTRE,
    (Zone.TOP_LEFT, Zone.BOTTOM_RIGHT): Zone.LEFT_TRANSITION,
    (Zone.TOP_LEFT, Zone.RIGHT_TRANSITION): Zone.LEFT_TRANSITION,
    (Zone.TOP_LEFT, Zone.YELLOW_START): Zone.TOP_CENTRE,
    (Zone.TOP_LEFT, Zone.YELLOW_TOP_CORNER): Zone.TOP_CENTRE,
    (Zone.TOP_RIGHT, Zone.RIGHT_TRANSITION): Zone.RIGHT_TRANSITION,
    (Zone.TOP_RIGHT, Zone.TOP_CENTRE): Zone.TOP_CENTRE,
    (Zone.TOP_RIGHT, Zone.YELLOW_START): Zone.YELLOW_START,
    (Zone.TOP_RIGHT, Zone.YELLOW_TOP_CORNER): Zone.YELLOW_TOP_CORNER,
    (Zone.TOP_RIGHT, Zone.BOTTOM_CENTRE): Zone.RIGHT_TRANSITION,
    (Zone.TOP_RIGHT, Zone.BOTTOM_RIGHT): Zone.RIGHT_TRANSITION,
    (Zone.TOP_RIGHT, Zone.TOP_LEFT): Zone.TOP_CENTRE,
    (Zone.TOP_RIGHT, Zone.BOTTOM_LEFT): Zone.RIGHT_TRANSITION,
    (Zone.TOP_RIGHT, Zone.LEFT_TRANSITION): Zone.RIGHT_TRANSITION,
    (Zone.TOP_RIGHT, Zone.PINK_START): Zone.TOP_CENTRE,
    (Zone.TOP_RIGHT, Zone.PINK_TOP_CORNER): Zone.TOP_CENTRE,
}

for (src, _), next_hop in ROUTING_POST_DROP.items():
    assert (src, next_hop) in STEERING_DIRECTIONS


def get_zone_steering(from_zone: Zone, to_loc: Location, dropped: bool) -> Optional[float]:
    to_zone = get_zone(to_loc)

    if from_zone == to_zone:
        return None

    routing_table = ROUTING_POST_DROP if dropped else ROUTING_PRE_DROP

    next_hop = routing_table[from_zone, to_zone]
    if next_hop == to_zone:
        return None

    print(f"Routing for {to_zone} via {next_hop} (from {from_zone})")
    return STEERING_DIRECTIONS[from_zone, next_hop]


def is_direct_routable(from_zone: Zone, to_loc: Location, dropped: bool) -> bool:
    to_zone = get_zone(to_loc)

    if from_zone == to_zone:
        return True

    routing_table = ROUTING_POST_DROP if dropped else ROUTING_PRE_DROP

    next_hop = routing_table[from_zone, to_zone]
    return next_hop == to_zone
