import enum
import math

from typing import Optional, Tuple

from albot.view import Location


class Zone(enum.Enum):
    PINK_START = 'PINK_START'
    BOTTOM_LEFT = 'BOTTOM_LEFT'
    BOTTOM_RIGHT = 'BOTTOM_RIGHT'
    BOTTOM_CENTRE_LOWER = 'BOTTOM_CENTRE_LOWER'
    BOTTOM_CENTRE_UPPER = 'BOTTOM_CENTRE_UPPER'
    YELLOW_START = 'YELLOW_START'
    PINK_TOP_CORNER = 'PINK_TOP_CORNER'
    YELLOW_TOP_CORNER = 'YELLOW_TOP_CORNER'
    TOP_CENTRE = 'TOP_CENTRE'
    TOP_LEFT = 'TOP_LEFT'
    TOP_RIGHT = 'TOP_RIGHT'
    LEFT_TRANSITION = 'LEFT_TRANSITION'
    RIGHT_TRANSITION = 'RIGHT_TRANSITION'


def get_zone(location: Location) -> Zone:
    if location.x < -5.575:
        if location.y > 2:
            return Zone.PINK_TOP_CORNER
        elif location.y < -2.6:
            return Zone.BOTTOM_LEFT
        else:
            return Zone.PINK_START
    elif location.x < -3.5:
        if location.y > 0.75:
            return Zone.TOP_LEFT
        elif location.y > -0.9:
            return Zone.LEFT_TRANSITION
        else:
            return Zone.BOTTOM_LEFT
    elif location.x < 3.5:
        if location.y > 0:
            return Zone.TOP_CENTRE
        elif location.y > -1:
            return Zone.BOTTOM_CENTRE_UPPER
        else:
            return Zone.BOTTOM_CENTRE_LOWER
    elif location.x < 5.575:
        if location.y > 0.75:
            return Zone.TOP_RIGHT
        elif location.y > -0.9:
            return Zone.RIGHT_TRANSITION
        else:
            return Zone.BOTTOM_RIGHT
    else:
        if location.y > 2:
            return Zone.YELLOW_TOP_CORNER
        elif location.y < -2.6:
            return Zone.BOTTOM_RIGHT
        else:
            return Zone.YELLOW_START


STEERING_DIRECTIONS = {
    (Zone.PINK_START, Zone.BOTTOM_LEFT): math.radians(180),
    (Zone.PINK_START, Zone.TOP_LEFT): math.radians(90),
    (Zone.PINK_START, Zone.PINK_TOP_CORNER): math.radians(0),
    (Zone.BOTTOM_LEFT, Zone.BOTTOM_CENTRE_LOWER): math.radians(90),
    (Zone.BOTTOM_RIGHT, Zone.BOTTOM_CENTRE_LOWER): math.radians(270),
    (Zone.BOTTOM_LEFT, Zone.BOTTOM_CENTRE_UPPER): math.radians(75),
    (Zone.BOTTOM_RIGHT, Zone.BOTTOM_CENTRE_UPPER): math.radians(285),
    (Zone.BOTTOM_CENTRE_UPPER, Zone.LEFT_TRANSITION): math.radians(290),
    (Zone.BOTTOM_CENTRE_UPPER, Zone.RIGHT_TRANSITION): math.radians(70),
    (Zone.YELLOW_START, Zone.BOTTOM_RIGHT): math.radians(180),
    (Zone.YELLOW_START, Zone.YELLOW_TOP_CORNER): math.radians(0),
    (Zone.YELLOW_START, Zone.TOP_RIGHT): math.radians(270),
    (Zone.PINK_TOP_CORNER, Zone.TOP_LEFT): math.radians(120),
    (Zone.YELLOW_TOP_CORNER, Zone.TOP_RIGHT): math.radians(240),
    (Zone.TOP_CENTRE, Zone.TOP_LEFT): math.radians(240),
    (Zone.TOP_CENTRE, Zone.TOP_RIGHT): math.radians(90),
    (Zone.TOP_LEFT, Zone.LEFT_TRANSITION): math.radians(180),
    (Zone.TOP_RIGHT, Zone.RIGHT_TRANSITION): math.radians(180),
    (Zone.LEFT_TRANSITION, Zone.BOTTOM_LEFT): math.radians(180),
    (Zone.RIGHT_TRANSITION, Zone.BOTTOM_RIGHT): math.radians(180),
    (Zone.PINK_START, Zone.LEFT_TRANSITION): math.radians(90),
    (Zone.YELLOW_START, Zone.RIGHT_TRANSITION): math.radians(270),
    (Zone.PINK_TOP_CORNER, Zone.LEFT_TRANSITION): math.radians(135),
    (Zone.YELLOW_TOP_CORNER, Zone.RIGHT_TRANSITION): math.radians(235),
    (Zone.BOTTOM_CENTRE_LOWER, Zone.BOTTOM_CENTRE_UPPER): math.radians(0),
    (Zone.BOTTOM_CENTRE_LOWER, Zone.LEFT_TRANSITION): math.radians(305),
    (Zone.BOTTOM_CENTRE_LOWER, Zone.RIGHT_TRANSITION): math.radians(45),
}

for (src, dst), angle in list(STEERING_DIRECTIONS.items()):
    STEERING_DIRECTIONS[dst, src] = (math.radians(180) + angle) % math.tau


ROUTING_PRE_DROP = {
    (Zone.PINK_START, Zone.PINK_TOP_CORNER): Zone.PINK_TOP_CORNER,
    (Zone.PINK_START, Zone.BOTTOM_LEFT): Zone.BOTTOM_LEFT,
    (Zone.PINK_START, Zone.BOTTOM_CENTRE_LOWER): Zone.BOTTOM_LEFT,
    (Zone.PINK_START, Zone.BOTTOM_CENTRE_UPPER): Zone.BOTTOM_LEFT,
    (Zone.PINK_START, Zone.BOTTOM_RIGHT): Zone.BOTTOM_LEFT,
    (Zone.PINK_START, Zone.LEFT_TRANSITION): Zone.BOTTOM_LEFT,
    (Zone.PINK_START, Zone.RIGHT_TRANSITION): Zone.BOTTOM_LEFT,
    (Zone.PINK_START, Zone.YELLOW_START): Zone.BOTTOM_LEFT,
    (Zone.PINK_START, Zone.TOP_LEFT): Zone.BOTTOM_LEFT,
    (Zone.PINK_START, Zone.TOP_RIGHT): Zone.BOTTOM_LEFT,
    (Zone.PINK_START, Zone.YELLOW_TOP_CORNER): Zone.BOTTOM_LEFT,
    (Zone.PINK_START, Zone.TOP_CENTRE): Zone.BOTTOM_LEFT,
    (Zone.PINK_TOP_CORNER, Zone.PINK_START): Zone.PINK_START,
    (Zone.PINK_TOP_CORNER, Zone.BOTTOM_LEFT): Zone.PINK_START,
    (Zone.PINK_TOP_CORNER, Zone.BOTTOM_CENTRE_LOWER): Zone.PINK_START,
    (Zone.PINK_TOP_CORNER, Zone.BOTTOM_CENTRE_UPPER): Zone.PINK_START,
    (Zone.PINK_TOP_CORNER, Zone.BOTTOM_RIGHT): Zone.PINK_START,
    (Zone.PINK_TOP_CORNER, Zone.LEFT_TRANSITION): Zone.PINK_START,
    (Zone.PINK_TOP_CORNER, Zone.RIGHT_TRANSITION): Zone.PINK_START,
    (Zone.PINK_TOP_CORNER, Zone.YELLOW_START): Zone.PINK_START,
    (Zone.PINK_TOP_CORNER, Zone.TOP_LEFT): Zone.PINK_START,
    (Zone.PINK_TOP_CORNER, Zone.TOP_RIGHT): Zone.PINK_START,
    (Zone.PINK_TOP_CORNER, Zone.YELLOW_TOP_CORNER): Zone.PINK_START,
    (Zone.PINK_TOP_CORNER, Zone.TOP_CENTRE): Zone.PINK_START,
    (Zone.BOTTOM_LEFT, Zone.PINK_START): Zone.PINK_START,
    (Zone.BOTTOM_LEFT, Zone.BOTTOM_CENTRE_LOWER): Zone.BOTTOM_CENTRE_LOWER,
    (Zone.BOTTOM_LEFT, Zone.BOTTOM_CENTRE_UPPER): Zone.BOTTOM_CENTRE_UPPER,
    (Zone.BOTTOM_LEFT, Zone.PINK_TOP_CORNER): Zone.PINK_START,
    (Zone.BOTTOM_LEFT, Zone.BOTTOM_RIGHT): Zone.BOTTOM_CENTRE_LOWER,
    (Zone.BOTTOM_LEFT, Zone.LEFT_TRANSITION): Zone.BOTTOM_CENTRE_UPPER,
    (Zone.BOTTOM_LEFT, Zone.RIGHT_TRANSITION): Zone.BOTTOM_CENTRE_UPPER,
    (Zone.BOTTOM_LEFT, Zone.YELLOW_START): Zone.BOTTOM_CENTRE_LOWER,
    (Zone.BOTTOM_LEFT, Zone.TOP_LEFT): Zone.BOTTOM_CENTRE_UPPER,
    (Zone.BOTTOM_LEFT, Zone.TOP_RIGHT): Zone.BOTTOM_CENTRE_UPPER,
    (Zone.BOTTOM_LEFT, Zone.YELLOW_TOP_CORNER): Zone.BOTTOM_CENTRE_LOWER,
    (Zone.BOTTOM_LEFT, Zone.TOP_CENTRE): Zone.BOTTOM_CENTRE_UPPER,
    (Zone.BOTTOM_CENTRE_LOWER, Zone.BOTTOM_LEFT): Zone.BOTTOM_LEFT,
    (Zone.BOTTOM_CENTRE_LOWER, Zone.BOTTOM_RIGHT): Zone.BOTTOM_RIGHT,
    (Zone.BOTTOM_CENTRE_LOWER, Zone.BOTTOM_CENTRE_UPPER): Zone.BOTTOM_CENTRE_UPPER,
    (Zone.BOTTOM_CENTRE_LOWER, Zone.PINK_START): Zone.BOTTOM_LEFT,
    (Zone.BOTTOM_CENTRE_LOWER, Zone.YELLOW_START): Zone.BOTTOM_RIGHT,
    (Zone.BOTTOM_CENTRE_LOWER, Zone.LEFT_TRANSITION): Zone.BOTTOM_CENTRE_UPPER,
    (Zone.BOTTOM_CENTRE_LOWER, Zone.RIGHT_TRANSITION): Zone.BOTTOM_CENTRE_UPPER,
    (Zone.BOTTOM_CENTRE_LOWER, Zone.PINK_TOP_CORNER): Zone.BOTTOM_LEFT,
    (Zone.BOTTOM_CENTRE_LOWER, Zone.YELLOW_TOP_CORNER): Zone.BOTTOM_RIGHT,
    (Zone.BOTTOM_CENTRE_LOWER, Zone.TOP_LEFT): Zone.BOTTOM_CENTRE_UPPER,
    (Zone.BOTTOM_CENTRE_LOWER, Zone.TOP_RIGHT): Zone.BOTTOM_CENTRE_UPPER,
    (Zone.BOTTOM_CENTRE_LOWER, Zone.TOP_CENTRE): Zone.BOTTOM_CENTRE_UPPER,
    (Zone.BOTTOM_CENTRE_UPPER, Zone.BOTTOM_LEFT): Zone.BOTTOM_LEFT,
    (Zone.BOTTOM_CENTRE_UPPER, Zone.BOTTOM_RIGHT): Zone.BOTTOM_RIGHT,
    (Zone.BOTTOM_CENTRE_UPPER, Zone.LEFT_TRANSITION): Zone.LEFT_TRANSITION,
    (Zone.BOTTOM_CENTRE_UPPER, Zone.RIGHT_TRANSITION): Zone.RIGHT_TRANSITION,
    (Zone.BOTTOM_CENTRE_UPPER, Zone.BOTTOM_CENTRE_LOWER): Zone.BOTTOM_CENTRE_LOWER,
    (Zone.BOTTOM_CENTRE_UPPER, Zone.PINK_START): Zone.BOTTOM_LEFT,
    (Zone.BOTTOM_CENTRE_UPPER, Zone.YELLOW_START): Zone.BOTTOM_RIGHT,
    (Zone.BOTTOM_CENTRE_UPPER, Zone.TOP_LEFT): Zone.LEFT_TRANSITION,
    (Zone.BOTTOM_CENTRE_UPPER, Zone.TOP_RIGHT): Zone.RIGHT_TRANSITION,
    (Zone.BOTTOM_CENTRE_UPPER, Zone.PINK_TOP_CORNER): Zone.BOTTOM_LEFT,
    (Zone.BOTTOM_CENTRE_UPPER, Zone.YELLOW_TOP_CORNER): Zone.BOTTOM_RIGHT,
    (Zone.BOTTOM_CENTRE_UPPER, Zone.TOP_CENTRE): Zone.LEFT_TRANSITION,
    (Zone.BOTTOM_RIGHT, Zone.BOTTOM_CENTRE_LOWER): Zone.BOTTOM_CENTRE_LOWER,
    (Zone.BOTTOM_RIGHT, Zone.BOTTOM_CENTRE_UPPER): Zone.BOTTOM_CENTRE_UPPER,
    (Zone.BOTTOM_RIGHT, Zone.YELLOW_START): Zone.YELLOW_START,
    (Zone.BOTTOM_RIGHT, Zone.BOTTOM_LEFT): Zone.BOTTOM_CENTRE_LOWER,
    (Zone.BOTTOM_RIGHT, Zone.LEFT_TRANSITION): Zone.BOTTOM_CENTRE_UPPER,
    (Zone.BOTTOM_RIGHT, Zone.RIGHT_TRANSITION): Zone.BOTTOM_CENTRE_UPPER,
    (Zone.BOTTOM_RIGHT, Zone.YELLOW_TOP_CORNER): Zone.YELLOW_START,
    (Zone.BOTTOM_RIGHT, Zone.PINK_START): Zone.BOTTOM_CENTRE_LOWER,
    (Zone.BOTTOM_RIGHT, Zone.TOP_LEFT): Zone.BOTTOM_CENTRE_UPPER,
    (Zone.BOTTOM_RIGHT, Zone.TOP_RIGHT): Zone.BOTTOM_CENTRE_UPPER,
    (Zone.BOTTOM_RIGHT, Zone.PINK_TOP_CORNER): Zone.BOTTOM_CENTRE_LOWER,
    (Zone.BOTTOM_RIGHT, Zone.TOP_CENTRE): Zone.BOTTOM_CENTRE_UPPER,
    (Zone.YELLOW_START, Zone.BOTTOM_RIGHT): Zone.BOTTOM_RIGHT,
    (Zone.YELLOW_START, Zone.YELLOW_TOP_CORNER): Zone.YELLOW_TOP_CORNER,
    (Zone.YELLOW_START, Zone.BOTTOM_CENTRE_LOWER): Zone.BOTTOM_RIGHT,
    (Zone.YELLOW_START, Zone.BOTTOM_CENTRE_UPPER): Zone.BOTTOM_RIGHT,
    (Zone.YELLOW_START, Zone.BOTTOM_LEFT): Zone.BOTTOM_RIGHT,
    (Zone.YELLOW_START, Zone.LEFT_TRANSITION): Zone.BOTTOM_RIGHT,
    (Zone.YELLOW_START, Zone.RIGHT_TRANSITION): Zone.BOTTOM_RIGHT,
    (Zone.YELLOW_START, Zone.PINK_START): Zone.BOTTOM_RIGHT,
    (Zone.YELLOW_START, Zone.TOP_LEFT): Zone.BOTTOM_RIGHT,
    (Zone.YELLOW_START, Zone.TOP_RIGHT): Zone.BOTTOM_RIGHT,
    (Zone.YELLOW_START, Zone.PINK_TOP_CORNER): Zone.BOTTOM_RIGHT,
    (Zone.YELLOW_START, Zone.TOP_CENTRE): Zone.BOTTOM_RIGHT,
    (Zone.YELLOW_TOP_CORNER, Zone.YELLOW_START): Zone.YELLOW_START,
    (Zone.YELLOW_TOP_CORNER, Zone.BOTTOM_RIGHT): Zone.YELLOW_START,
    (Zone.YELLOW_TOP_CORNER, Zone.BOTTOM_CENTRE_LOWER): Zone.YELLOW_START,
    (Zone.YELLOW_TOP_CORNER, Zone.BOTTOM_CENTRE_UPPER): Zone.YELLOW_START,
    (Zone.YELLOW_TOP_CORNER, Zone.BOTTOM_LEFT): Zone.YELLOW_START,
    (Zone.YELLOW_TOP_CORNER, Zone.LEFT_TRANSITION): Zone.YELLOW_START,
    (Zone.YELLOW_TOP_CORNER, Zone.RIGHT_TRANSITION): Zone.YELLOW_START,
    (Zone.YELLOW_TOP_CORNER, Zone.PINK_START): Zone.YELLOW_START,
    (Zone.YELLOW_TOP_CORNER, Zone.TOP_LEFT): Zone.YELLOW_START,
    (Zone.YELLOW_TOP_CORNER, Zone.TOP_RIGHT): Zone.YELLOW_START,
    (Zone.YELLOW_TOP_CORNER, Zone.PINK_TOP_CORNER): Zone.YELLOW_START,
    (Zone.YELLOW_TOP_CORNER, Zone.TOP_CENTRE): Zone.YELLOW_START,
    (Zone.LEFT_TRANSITION, Zone.BOTTOM_CENTRE_UPPER): Zone.BOTTOM_CENTRE_UPPER,
    (Zone.LEFT_TRANSITION, Zone.TOP_LEFT): Zone.TOP_LEFT,
    (Zone.LEFT_TRANSITION, Zone.BOTTOM_LEFT): Zone.BOTTOM_CENTRE_UPPER,
    (Zone.LEFT_TRANSITION, Zone.BOTTOM_RIGHT): Zone.BOTTOM_CENTRE_UPPER,
    (Zone.LEFT_TRANSITION, Zone.RIGHT_TRANSITION): Zone.BOTTOM_CENTRE_UPPER,
    (Zone.LEFT_TRANSITION, Zone.BOTTOM_CENTRE_LOWER): Zone.BOTTOM_CENTRE_UPPER,
    (Zone.LEFT_TRANSITION, Zone.TOP_CENTRE): Zone.TOP_LEFT,
    (Zone.LEFT_TRANSITION, Zone.PINK_START): Zone.BOTTOM_CENTRE_UPPER,
    (Zone.LEFT_TRANSITION, Zone.YELLOW_START): Zone.BOTTOM_CENTRE_UPPER,
    (Zone.LEFT_TRANSITION, Zone.TOP_RIGHT): Zone.BOTTOM_CENTRE_UPPER,
    (Zone.LEFT_TRANSITION, Zone.PINK_TOP_CORNER): Zone.BOTTOM_CENTRE_UPPER,
    (Zone.LEFT_TRANSITION, Zone.YELLOW_TOP_CORNER): Zone.BOTTOM_CENTRE_UPPER,
    (Zone.RIGHT_TRANSITION, Zone.BOTTOM_CENTRE_UPPER): Zone.BOTTOM_CENTRE_UPPER,
    (Zone.RIGHT_TRANSITION, Zone.TOP_RIGHT): Zone.TOP_RIGHT,
    (Zone.RIGHT_TRANSITION, Zone.BOTTOM_LEFT): Zone.BOTTOM_CENTRE_UPPER,
    (Zone.RIGHT_TRANSITION, Zone.BOTTOM_RIGHT): Zone.BOTTOM_CENTRE_UPPER,
    (Zone.RIGHT_TRANSITION, Zone.LEFT_TRANSITION): Zone.BOTTOM_CENTRE_UPPER,
    (Zone.RIGHT_TRANSITION, Zone.BOTTOM_CENTRE_LOWER): Zone.BOTTOM_CENTRE_UPPER,
    (Zone.RIGHT_TRANSITION, Zone.TOP_CENTRE): Zone.TOP_RIGHT,
    (Zone.RIGHT_TRANSITION, Zone.PINK_START): Zone.BOTTOM_CENTRE_UPPER,
    (Zone.RIGHT_TRANSITION, Zone.YELLOW_START): Zone.BOTTOM_CENTRE_UPPER,
    (Zone.RIGHT_TRANSITION, Zone.TOP_LEFT): Zone.BOTTOM_CENTRE_UPPER,
    (Zone.RIGHT_TRANSITION, Zone.PINK_TOP_CORNER): Zone.BOTTOM_CENTRE_UPPER,
    (Zone.RIGHT_TRANSITION, Zone.YELLOW_TOP_CORNER): Zone.BOTTOM_CENTRE_UPPER,
    (Zone.TOP_LEFT, Zone.LEFT_TRANSITION): Zone.LEFT_TRANSITION,
    (Zone.TOP_LEFT, Zone.TOP_CENTRE): Zone.TOP_CENTRE,
    (Zone.TOP_LEFT, Zone.BOTTOM_CENTRE_UPPER): Zone.LEFT_TRANSITION,
    (Zone.TOP_LEFT, Zone.TOP_RIGHT): Zone.TOP_CENTRE,
    (Zone.TOP_LEFT, Zone.BOTTOM_LEFT): Zone.LEFT_TRANSITION,
    (Zone.TOP_LEFT, Zone.BOTTOM_RIGHT): Zone.LEFT_TRANSITION,
    (Zone.TOP_LEFT, Zone.RIGHT_TRANSITION): Zone.LEFT_TRANSITION,
    (Zone.TOP_LEFT, Zone.BOTTOM_CENTRE_LOWER): Zone.LEFT_TRANSITION,
    (Zone.TOP_LEFT, Zone.PINK_START): Zone.LEFT_TRANSITION,
    (Zone.TOP_LEFT, Zone.YELLOW_START): Zone.LEFT_TRANSITION,
    (Zone.TOP_LEFT, Zone.PINK_TOP_CORNER): Zone.LEFT_TRANSITION,
    (Zone.TOP_LEFT, Zone.YELLOW_TOP_CORNER): Zone.LEFT_TRANSITION,
    (Zone.TOP_RIGHT, Zone.RIGHT_TRANSITION): Zone.RIGHT_TRANSITION,
    (Zone.TOP_RIGHT, Zone.TOP_CENTRE): Zone.TOP_CENTRE,
    (Zone.TOP_RIGHT, Zone.BOTTOM_CENTRE_UPPER): Zone.RIGHT_TRANSITION,
    (Zone.TOP_RIGHT, Zone.TOP_LEFT): Zone.TOP_CENTRE,
    (Zone.TOP_RIGHT, Zone.BOTTOM_LEFT): Zone.RIGHT_TRANSITION,
    (Zone.TOP_RIGHT, Zone.BOTTOM_RIGHT): Zone.RIGHT_TRANSITION,
    (Zone.TOP_RIGHT, Zone.LEFT_TRANSITION): Zone.RIGHT_TRANSITION,
    (Zone.TOP_RIGHT, Zone.BOTTOM_CENTRE_LOWER): Zone.RIGHT_TRANSITION,
    (Zone.TOP_RIGHT, Zone.PINK_START): Zone.RIGHT_TRANSITION,
    (Zone.TOP_RIGHT, Zone.YELLOW_START): Zone.RIGHT_TRANSITION,
    (Zone.TOP_RIGHT, Zone.PINK_TOP_CORNER): Zone.RIGHT_TRANSITION,
    (Zone.TOP_RIGHT, Zone.YELLOW_TOP_CORNER): Zone.RIGHT_TRANSITION,
    (Zone.TOP_CENTRE, Zone.TOP_LEFT): Zone.TOP_LEFT,
    (Zone.TOP_CENTRE, Zone.TOP_RIGHT): Zone.TOP_RIGHT,
    (Zone.TOP_CENTRE, Zone.LEFT_TRANSITION): Zone.TOP_LEFT,
    (Zone.TOP_CENTRE, Zone.RIGHT_TRANSITION): Zone.TOP_RIGHT,
    (Zone.TOP_CENTRE, Zone.BOTTOM_CENTRE_UPPER): Zone.TOP_LEFT,
    (Zone.TOP_CENTRE, Zone.BOTTOM_LEFT): Zone.TOP_LEFT,
    (Zone.TOP_CENTRE, Zone.BOTTOM_RIGHT): Zone.TOP_LEFT,
    (Zone.TOP_CENTRE, Zone.BOTTOM_CENTRE_LOWER): Zone.TOP_LEFT,
    (Zone.TOP_CENTRE, Zone.PINK_START): Zone.TOP_LEFT,
    (Zone.TOP_CENTRE, Zone.YELLOW_START): Zone.TOP_LEFT,
    (Zone.TOP_CENTRE, Zone.PINK_TOP_CORNER): Zone.TOP_LEFT,
    (Zone.TOP_CENTRE, Zone.YELLOW_TOP_CORNER): Zone.TOP_LEFT,
}

ROUTING_POST_DROP = {
    (Zone.PINK_START, Zone.PINK_TOP_CORNER): Zone.PINK_TOP_CORNER,
    (Zone.PINK_START, Zone.BOTTOM_LEFT): Zone.BOTTOM_LEFT,
    (Zone.PINK_START, Zone.LEFT_TRANSITION): Zone.LEFT_TRANSITION,
    (Zone.PINK_START, Zone.TOP_LEFT): Zone.TOP_LEFT,
    (Zone.PINK_START, Zone.BOTTOM_CENTRE_LOWER): Zone.BOTTOM_LEFT,
    (Zone.PINK_START, Zone.BOTTOM_CENTRE_UPPER): Zone.BOTTOM_LEFT,
    (Zone.PINK_START, Zone.TOP_CENTRE): Zone.TOP_LEFT,
    (Zone.PINK_START, Zone.BOTTOM_RIGHT): Zone.BOTTOM_LEFT,
    (Zone.PINK_START, Zone.RIGHT_TRANSITION): Zone.BOTTOM_LEFT,
    (Zone.PINK_START, Zone.TOP_RIGHT): Zone.TOP_LEFT,
    (Zone.PINK_START, Zone.YELLOW_START): Zone.BOTTOM_LEFT,
    (Zone.PINK_START, Zone.YELLOW_TOP_CORNER): Zone.BOTTOM_LEFT,
    (Zone.PINK_TOP_CORNER, Zone.PINK_START): Zone.PINK_START,
    (Zone.PINK_TOP_CORNER, Zone.LEFT_TRANSITION): Zone.LEFT_TRANSITION,
    (Zone.PINK_TOP_CORNER, Zone.TOP_LEFT): Zone.TOP_LEFT,
    (Zone.PINK_TOP_CORNER, Zone.BOTTOM_LEFT): Zone.PINK_START,
    (Zone.PINK_TOP_CORNER, Zone.BOTTOM_CENTRE_UPPER): Zone.LEFT_TRANSITION,
    (Zone.PINK_TOP_CORNER, Zone.BOTTOM_CENTRE_LOWER): Zone.LEFT_TRANSITION,
    (Zone.PINK_TOP_CORNER, Zone.TOP_CENTRE): Zone.TOP_LEFT,
    (Zone.PINK_TOP_CORNER, Zone.BOTTOM_RIGHT): Zone.LEFT_TRANSITION,
    (Zone.PINK_TOP_CORNER, Zone.RIGHT_TRANSITION): Zone.LEFT_TRANSITION,
    (Zone.PINK_TOP_CORNER, Zone.TOP_RIGHT): Zone.TOP_LEFT,
    (Zone.PINK_TOP_CORNER, Zone.YELLOW_START): Zone.LEFT_TRANSITION,
    (Zone.PINK_TOP_CORNER, Zone.YELLOW_TOP_CORNER): Zone.LEFT_TRANSITION,
    (Zone.BOTTOM_LEFT, Zone.PINK_START): Zone.PINK_START,
    (Zone.BOTTOM_LEFT, Zone.BOTTOM_CENTRE_LOWER): Zone.BOTTOM_CENTRE_LOWER,
    (Zone.BOTTOM_LEFT, Zone.BOTTOM_CENTRE_UPPER): Zone.BOTTOM_CENTRE_UPPER,
    (Zone.BOTTOM_LEFT, Zone.LEFT_TRANSITION): Zone.LEFT_TRANSITION,
    (Zone.BOTTOM_LEFT, Zone.PINK_TOP_CORNER): Zone.PINK_START,
    (Zone.BOTTOM_LEFT, Zone.TOP_LEFT): Zone.PINK_START,
    (Zone.BOTTOM_LEFT, Zone.BOTTOM_RIGHT): Zone.BOTTOM_CENTRE_LOWER,
    (Zone.BOTTOM_LEFT, Zone.RIGHT_TRANSITION): Zone.BOTTOM_CENTRE_LOWER,
    (Zone.BOTTOM_LEFT, Zone.TOP_CENTRE): Zone.PINK_START,
    (Zone.BOTTOM_LEFT, Zone.YELLOW_START): Zone.BOTTOM_CENTRE_LOWER,
    (Zone.BOTTOM_LEFT, Zone.TOP_RIGHT): Zone.BOTTOM_CENTRE_LOWER,
    (Zone.BOTTOM_LEFT, Zone.YELLOW_TOP_CORNER): Zone.BOTTOM_CENTRE_LOWER,
    (Zone.BOTTOM_CENTRE_LOWER, Zone.BOTTOM_LEFT): Zone.BOTTOM_LEFT,
    (Zone.BOTTOM_CENTRE_LOWER, Zone.BOTTOM_RIGHT): Zone.BOTTOM_RIGHT,
    (Zone.BOTTOM_CENTRE_LOWER, Zone.BOTTOM_CENTRE_UPPER): Zone.BOTTOM_CENTRE_UPPER,
    (Zone.BOTTOM_CENTRE_LOWER, Zone.LEFT_TRANSITION): Zone.LEFT_TRANSITION,
    (Zone.BOTTOM_CENTRE_LOWER, Zone.RIGHT_TRANSITION): Zone.RIGHT_TRANSITION,
    (Zone.BOTTOM_CENTRE_LOWER, Zone.PINK_START): Zone.BOTTOM_LEFT,
    (Zone.BOTTOM_CENTRE_LOWER, Zone.YELLOW_START): Zone.BOTTOM_RIGHT,
    (Zone.BOTTOM_CENTRE_LOWER, Zone.TOP_LEFT): Zone.LEFT_TRANSITION,
    (Zone.BOTTOM_CENTRE_LOWER, Zone.PINK_TOP_CORNER): Zone.LEFT_TRANSITION,
    (Zone.BOTTOM_CENTRE_LOWER, Zone.TOP_RIGHT): Zone.RIGHT_TRANSITION,
    (Zone.BOTTOM_CENTRE_LOWER, Zone.YELLOW_TOP_CORNER): Zone.RIGHT_TRANSITION,
    (Zone.BOTTOM_CENTRE_LOWER, Zone.TOP_CENTRE): Zone.LEFT_TRANSITION,
    (Zone.BOTTOM_CENTRE_UPPER, Zone.BOTTOM_LEFT): Zone.BOTTOM_LEFT,
    (Zone.BOTTOM_CENTRE_UPPER, Zone.BOTTOM_RIGHT): Zone.BOTTOM_RIGHT,
    (Zone.BOTTOM_CENTRE_UPPER, Zone.LEFT_TRANSITION): Zone.LEFT_TRANSITION,
    (Zone.BOTTOM_CENTRE_UPPER, Zone.RIGHT_TRANSITION): Zone.RIGHT_TRANSITION,
    (Zone.BOTTOM_CENTRE_UPPER, Zone.BOTTOM_CENTRE_LOWER): Zone.BOTTOM_CENTRE_LOWER,
    (Zone.BOTTOM_CENTRE_UPPER, Zone.PINK_START): Zone.BOTTOM_LEFT,
    (Zone.BOTTOM_CENTRE_UPPER, Zone.YELLOW_START): Zone.BOTTOM_RIGHT,
    (Zone.BOTTOM_CENTRE_UPPER, Zone.TOP_LEFT): Zone.LEFT_TRANSITION,
    (Zone.BOTTOM_CENTRE_UPPER, Zone.PINK_TOP_CORNER): Zone.LEFT_TRANSITION,
    (Zone.BOTTOM_CENTRE_UPPER, Zone.TOP_RIGHT): Zone.RIGHT_TRANSITION,
    (Zone.BOTTOM_CENTRE_UPPER, Zone.YELLOW_TOP_CORNER): Zone.RIGHT_TRANSITION,
    (Zone.BOTTOM_CENTRE_UPPER, Zone.TOP_CENTRE): Zone.LEFT_TRANSITION,
    (Zone.BOTTOM_RIGHT, Zone.BOTTOM_CENTRE_LOWER): Zone.BOTTOM_CENTRE_LOWER,
    (Zone.BOTTOM_RIGHT, Zone.BOTTOM_CENTRE_UPPER): Zone.BOTTOM_CENTRE_UPPER,
    (Zone.BOTTOM_RIGHT, Zone.YELLOW_START): Zone.YELLOW_START,
    (Zone.BOTTOM_RIGHT, Zone.RIGHT_TRANSITION): Zone.RIGHT_TRANSITION,
    (Zone.BOTTOM_RIGHT, Zone.BOTTOM_LEFT): Zone.BOTTOM_CENTRE_LOWER,
    (Zone.BOTTOM_RIGHT, Zone.LEFT_TRANSITION): Zone.BOTTOM_CENTRE_LOWER,
    (Zone.BOTTOM_RIGHT, Zone.YELLOW_TOP_CORNER): Zone.YELLOW_START,
    (Zone.BOTTOM_RIGHT, Zone.TOP_RIGHT): Zone.YELLOW_START,
    (Zone.BOTTOM_RIGHT, Zone.PINK_START): Zone.BOTTOM_CENTRE_LOWER,
    (Zone.BOTTOM_RIGHT, Zone.TOP_LEFT): Zone.BOTTOM_CENTRE_LOWER,
    (Zone.BOTTOM_RIGHT, Zone.PINK_TOP_CORNER): Zone.BOTTOM_CENTRE_LOWER,
    (Zone.BOTTOM_RIGHT, Zone.TOP_CENTRE): Zone.YELLOW_START,
    (Zone.YELLOW_START, Zone.BOTTOM_RIGHT): Zone.BOTTOM_RIGHT,
    (Zone.YELLOW_START, Zone.YELLOW_TOP_CORNER): Zone.YELLOW_TOP_CORNER,
    (Zone.YELLOW_START, Zone.RIGHT_TRANSITION): Zone.RIGHT_TRANSITION,
    (Zone.YELLOW_START, Zone.TOP_RIGHT): Zone.TOP_RIGHT,
    (Zone.YELLOW_START, Zone.BOTTOM_CENTRE_LOWER): Zone.BOTTOM_RIGHT,
    (Zone.YELLOW_START, Zone.BOTTOM_CENTRE_UPPER): Zone.BOTTOM_RIGHT,
    (Zone.YELLOW_START, Zone.TOP_CENTRE): Zone.TOP_RIGHT,
    (Zone.YELLOW_START, Zone.BOTTOM_LEFT): Zone.BOTTOM_RIGHT,
    (Zone.YELLOW_START, Zone.LEFT_TRANSITION): Zone.BOTTOM_RIGHT,
    (Zone.YELLOW_START, Zone.TOP_LEFT): Zone.TOP_RIGHT,
    (Zone.YELLOW_START, Zone.PINK_START): Zone.BOTTOM_RIGHT,
    (Zone.YELLOW_START, Zone.PINK_TOP_CORNER): Zone.BOTTOM_RIGHT,
    (Zone.YELLOW_TOP_CORNER, Zone.YELLOW_START): Zone.YELLOW_START,
    (Zone.YELLOW_TOP_CORNER, Zone.RIGHT_TRANSITION): Zone.RIGHT_TRANSITION,
    (Zone.YELLOW_TOP_CORNER, Zone.TOP_RIGHT): Zone.TOP_RIGHT,
    (Zone.YELLOW_TOP_CORNER, Zone.BOTTOM_RIGHT): Zone.YELLOW_START,
    (Zone.YELLOW_TOP_CORNER, Zone.BOTTOM_CENTRE_UPPER): Zone.RIGHT_TRANSITION,
    (Zone.YELLOW_TOP_CORNER, Zone.BOTTOM_CENTRE_LOWER): Zone.RIGHT_TRANSITION,
    (Zone.YELLOW_TOP_CORNER, Zone.TOP_CENTRE): Zone.TOP_RIGHT,
    (Zone.YELLOW_TOP_CORNER, Zone.BOTTOM_LEFT): Zone.RIGHT_TRANSITION,
    (Zone.YELLOW_TOP_CORNER, Zone.LEFT_TRANSITION): Zone.RIGHT_TRANSITION,
    (Zone.YELLOW_TOP_CORNER, Zone.TOP_LEFT): Zone.TOP_RIGHT,
    (Zone.YELLOW_TOP_CORNER, Zone.PINK_START): Zone.RIGHT_TRANSITION,
    (Zone.YELLOW_TOP_CORNER, Zone.PINK_TOP_CORNER): Zone.RIGHT_TRANSITION,
    (Zone.LEFT_TRANSITION, Zone.BOTTOM_CENTRE_UPPER): Zone.BOTTOM_CENTRE_UPPER,
    (Zone.LEFT_TRANSITION, Zone.TOP_LEFT): Zone.TOP_LEFT,
    (Zone.LEFT_TRANSITION, Zone.PINK_START): Zone.PINK_START,
    (Zone.LEFT_TRANSITION, Zone.PINK_TOP_CORNER): Zone.PINK_TOP_CORNER,
    (Zone.LEFT_TRANSITION, Zone.BOTTOM_LEFT): Zone.BOTTOM_LEFT,
    (Zone.LEFT_TRANSITION, Zone.BOTTOM_CENTRE_LOWER): Zone.BOTTOM_CENTRE_LOWER,
    (Zone.LEFT_TRANSITION, Zone.BOTTOM_RIGHT): Zone.BOTTOM_CENTRE_UPPER,
    (Zone.LEFT_TRANSITION, Zone.RIGHT_TRANSITION): Zone.BOTTOM_CENTRE_UPPER,
    (Zone.LEFT_TRANSITION, Zone.TOP_CENTRE): Zone.TOP_LEFT,
    (Zone.LEFT_TRANSITION, Zone.YELLOW_START): Zone.BOTTOM_CENTRE_UPPER,
    (Zone.LEFT_TRANSITION, Zone.TOP_RIGHT): Zone.BOTTOM_CENTRE_UPPER,
    (Zone.LEFT_TRANSITION, Zone.YELLOW_TOP_CORNER): Zone.BOTTOM_CENTRE_UPPER,
    (Zone.RIGHT_TRANSITION, Zone.BOTTOM_CENTRE_UPPER): Zone.BOTTOM_CENTRE_UPPER,
    (Zone.RIGHT_TRANSITION, Zone.TOP_RIGHT): Zone.TOP_RIGHT,
    (Zone.RIGHT_TRANSITION, Zone.YELLOW_START): Zone.YELLOW_START,
    (Zone.RIGHT_TRANSITION, Zone.YELLOW_TOP_CORNER): Zone.YELLOW_TOP_CORNER,
    (Zone.RIGHT_TRANSITION, Zone.BOTTOM_RIGHT): Zone.BOTTOM_RIGHT,
    (Zone.RIGHT_TRANSITION, Zone.BOTTOM_CENTRE_LOWER): Zone.BOTTOM_CENTRE_LOWER,
    (Zone.RIGHT_TRANSITION, Zone.BOTTOM_LEFT): Zone.BOTTOM_CENTRE_UPPER,
    (Zone.RIGHT_TRANSITION, Zone.LEFT_TRANSITION): Zone.BOTTOM_CENTRE_UPPER,
    (Zone.RIGHT_TRANSITION, Zone.TOP_CENTRE): Zone.TOP_RIGHT,
    (Zone.RIGHT_TRANSITION, Zone.PINK_START): Zone.BOTTOM_CENTRE_UPPER,
    (Zone.RIGHT_TRANSITION, Zone.TOP_LEFT): Zone.BOTTOM_CENTRE_UPPER,
    (Zone.RIGHT_TRANSITION, Zone.PINK_TOP_CORNER): Zone.BOTTOM_CENTRE_UPPER,
    (Zone.TOP_LEFT, Zone.LEFT_TRANSITION): Zone.LEFT_TRANSITION,
    (Zone.TOP_LEFT, Zone.TOP_CENTRE): Zone.TOP_CENTRE,
    (Zone.TOP_LEFT, Zone.PINK_START): Zone.PINK_START,
    (Zone.TOP_LEFT, Zone.PINK_TOP_CORNER): Zone.PINK_TOP_CORNER,
    (Zone.TOP_LEFT, Zone.BOTTOM_CENTRE_UPPER): Zone.LEFT_TRANSITION,
    (Zone.TOP_LEFT, Zone.BOTTOM_LEFT): Zone.LEFT_TRANSITION,
    (Zone.TOP_LEFT, Zone.BOTTOM_CENTRE_LOWER): Zone.LEFT_TRANSITION,
    (Zone.TOP_LEFT, Zone.TOP_RIGHT): Zone.TOP_CENTRE,
    (Zone.TOP_LEFT, Zone.BOTTOM_RIGHT): Zone.LEFT_TRANSITION,
    (Zone.TOP_LEFT, Zone.RIGHT_TRANSITION): Zone.LEFT_TRANSITION,
    (Zone.TOP_LEFT, Zone.YELLOW_START): Zone.TOP_CENTRE,
    (Zone.TOP_LEFT, Zone.YELLOW_TOP_CORNER): Zone.TOP_CENTRE,
    (Zone.TOP_RIGHT, Zone.RIGHT_TRANSITION): Zone.RIGHT_TRANSITION,
    (Zone.TOP_RIGHT, Zone.TOP_CENTRE): Zone.TOP_CENTRE,
    (Zone.TOP_RIGHT, Zone.YELLOW_START): Zone.YELLOW_START,
    (Zone.TOP_RIGHT, Zone.YELLOW_TOP_CORNER): Zone.YELLOW_TOP_CORNER,
    (Zone.TOP_RIGHT, Zone.BOTTOM_CENTRE_UPPER): Zone.RIGHT_TRANSITION,
    (Zone.TOP_RIGHT, Zone.BOTTOM_RIGHT): Zone.RIGHT_TRANSITION,
    (Zone.TOP_RIGHT, Zone.BOTTOM_CENTRE_LOWER): Zone.RIGHT_TRANSITION,
    (Zone.TOP_RIGHT, Zone.TOP_LEFT): Zone.TOP_CENTRE,
    (Zone.TOP_RIGHT, Zone.BOTTOM_LEFT): Zone.RIGHT_TRANSITION,
    (Zone.TOP_RIGHT, Zone.LEFT_TRANSITION): Zone.RIGHT_TRANSITION,
    (Zone.TOP_RIGHT, Zone.PINK_START): Zone.TOP_CENTRE,
    (Zone.TOP_RIGHT, Zone.PINK_TOP_CORNER): Zone.TOP_CENTRE,
    (Zone.TOP_CENTRE, Zone.TOP_LEFT): Zone.TOP_LEFT,
    (Zone.TOP_CENTRE, Zone.TOP_RIGHT): Zone.TOP_RIGHT,
    (Zone.TOP_CENTRE, Zone.LEFT_TRANSITION): Zone.TOP_LEFT,
    (Zone.TOP_CENTRE, Zone.PINK_START): Zone.TOP_LEFT,
    (Zone.TOP_CENTRE, Zone.PINK_TOP_CORNER): Zone.TOP_LEFT,
    (Zone.TOP_CENTRE, Zone.RIGHT_TRANSITION): Zone.TOP_RIGHT,
    (Zone.TOP_CENTRE, Zone.YELLOW_START): Zone.TOP_RIGHT,
    (Zone.TOP_CENTRE, Zone.YELLOW_TOP_CORNER): Zone.TOP_RIGHT,
    (Zone.TOP_CENTRE, Zone.BOTTOM_CENTRE_UPPER): Zone.TOP_LEFT,
    (Zone.TOP_CENTRE, Zone.BOTTOM_LEFT): Zone.TOP_LEFT,
    (Zone.TOP_CENTRE, Zone.BOTTOM_CENTRE_LOWER): Zone.TOP_LEFT,
    (Zone.TOP_CENTRE, Zone.BOTTOM_RIGHT): Zone.TOP_RIGHT,
}


for table in (ROUTING_POST_DROP, ROUTING_PRE_DROP):
    for (src, _), next_hop in table.items():
        if (src, next_hop) not in STEERING_DIRECTIONS:
            raise AssertionError(f"Missing steering {src}>{next_hop}")


def get_next_hop(from_zone: Zone, to_loc: Location, dropped: bool) -> Tuple[Zone, bool]:
    to_zone = get_zone(to_loc)

    if from_zone == to_zone:
        return True

    routing_table = ROUTING_POST_DROP if dropped else ROUTING_PRE_DROP

    next_hop = routing_table[from_zone, to_zone]
    return next_hop, next_hop == to_zone


def get_zone_steering(from_zone: Zone, to_loc: Location, dropped: bool) -> Optional[float]:
    next_hop, is_direct = get_next_hop(from_zone, to_loc, dropped)
    if is_direct:
        return None
    return STEERING_DIRECTIONS[from_zone, next_hop]


def is_direct_routable(from_zone: Zone, to_loc: Location, dropped: bool) -> bool:
    return get_next_hop(from_zone, to_loc, dropped)[1]
